### ISSUE TITLE
input shape

### ISSUE THREAD

**Issue by ThanhLV97** [Debapriya-Tula/Face-Verification#1]
i run your code on colab to train my data 
but i get an error, i checked and try to fix it, but i dont understand and the problem not resolve  
please help me
Error when checking input: expected anchor to have 4 dimensions, but got array with shape (0, 1)

**Comment by Debapriya-Tula** [comment]
My bad. As I was appending anchors to a list, the final NumPy array expected as input for the model was a list with shape (dataset_size,). So, we need to convert the list into a NumPy array by writing: anchors = np.array(anchors). I fixed some small errors also. Hope this helps. If yes, do close the issue.

P.S. Ensure the images you create for a dataset are all of shape (200, 180, 3) as they are padded later on.

**Comment by ThanhLV97** [comment]
oke, tks a lots
but i trained my model but i got the model sizes is 1.5G 
it was large 
that is the error right?

**Comment by Debapriya-Tula** [comment]
The model's large indeed as I am using a VGG16 model as the base model for the network. But that is not an error per se. You can try transfer learning on this by setting layers' trainable parameter to False for the layers in the fore.
