### ISSUE TITLE
compare_face funcntion

### ISSUE THREAD

**Issue by ThanhLV97** [Debapriya-Tula/Face-Verification#2]
hi
i have a question about compare_face function  in your code 
https://github.com/Debapriya-Tula/Face-Verification/blob/b20b61e0d06ef448386f7e6b44cea313ffbecbc9/detect_and_verify.py#L100

the function was not defined in your code and i check but dont saw any package
i dont understand, can you explain that 
tks

**Comment by Debapriya-Tula** [comment]
My bad. It should be 'verify_face' not 'compare_face'. The 'verify_face' function is defined in the same file.
